In [3]:
import numpy as np

In [6]:

def strategy(M,turn,n):
    
    
    
    if turn==n*n: #To stop the game when need and assign the winner
        print()
        if np.linalg.det(M)==0:
            print('0 wins')
        if np.linalg.det(M)!=0:
            print('1 wins')
    elif turn == 0 or turn%2==0:# determine who's go it is
        r = int(input('What row would you like to go?'))
        c = int(input('What column would you like to go?'))
        M[r-1][c-1]=0 #Place a 0 in the nessesary place
        turn=turn+1
        print(M)
        strategy(M,turn,n) #Progress the game to the next turn
    else:
        r = int(input('What row would you like to go?'))
        c = int(input('What column would you like to go?'))
        M[r-1][c-1]=1
        turn=turn+1
        print(M)
        strategy(M,turn,n)

    

In [7]:
M=np.empty([2,2])+5 # Generate the starting matrix, 5 is added it differentiate between elements chosen and not chosen.
strategy(M,0,2) #M and n msut be changed depending on the size of the grid

What row would you like to go?1
What column would you like to go?1
[[0.00000000e+000 5.00000000e+000]
 [2.03541648e+236 2.43400036e+159]]
What row would you like to go?1
What column would you like to go?2
[[0.00000000e+000 1.00000000e+000]
 [2.03541648e+236 2.43400036e+159]]
What row would you like to go?2
What column would you like to go?1
[[0.00000000e+000 1.00000000e+000]
 [0.00000000e+000 2.43400036e+159]]
What row would you like to go?2
What column would you like to go?2
[[0. 1.]
 [0. 1.]]

0 wins
